apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: {{ .Release.Name }}-ssvc
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 8080 
  type: {{ .Values.service.type }} # type of the service.